# Site settings
title: Shi Qiu
description: A blog about Shi Qiu

# User settings
username: Shi Qiu
user_description: 
user_title: Research Assistant Professor in Remote Sensing
email: shi.qiu@uconn.com
twitter_username: lorem_ipsum
github_username: https://github.com/shi-eo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
